name: Build and Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: stable
            - run: go mod tidy
            - name: Setup Postegres
              run: scripts/test_setup.sh
              shell: bash
            - run: go test -v ./...
            - name: Shutdown Postgres
              run: scripts/test_shutdown.sh
              shell: bash